/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LukasakovaAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface LukasakovaAmbulanceWlEditor {
        "entryId": string;
    }
    interface LukasakovaAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface LukasakovaAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLukasakovaAmbulanceWlEditorElement;
}
export interface LukasakovaAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLukasakovaAmbulanceWlListElement;
}
declare global {
    interface HTMLLukasakovaAmbulanceWlAppElement extends Components.LukasakovaAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLLukasakovaAmbulanceWlAppElement: {
        prototype: HTMLLukasakovaAmbulanceWlAppElement;
        new (): HTMLLukasakovaAmbulanceWlAppElement;
    };
    interface HTMLLukasakovaAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLLukasakovaAmbulanceWlEditorElement extends Components.LukasakovaAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLukasakovaAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLLukasakovaAmbulanceWlEditorElement, ev: LukasakovaAmbulanceWlEditorCustomEvent<HTMLLukasakovaAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLukasakovaAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLLukasakovaAmbulanceWlEditorElement, ev: LukasakovaAmbulanceWlEditorCustomEvent<HTMLLukasakovaAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLukasakovaAmbulanceWlEditorElement: {
        prototype: HTMLLukasakovaAmbulanceWlEditorElement;
        new (): HTMLLukasakovaAmbulanceWlEditorElement;
    };
    interface HTMLLukasakovaAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLLukasakovaAmbulanceWlListElement extends Components.LukasakovaAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLukasakovaAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLLukasakovaAmbulanceWlListElement, ev: LukasakovaAmbulanceWlListCustomEvent<HTMLLukasakovaAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLukasakovaAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLLukasakovaAmbulanceWlListElement, ev: LukasakovaAmbulanceWlListCustomEvent<HTMLLukasakovaAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLukasakovaAmbulanceWlListElement: {
        prototype: HTMLLukasakovaAmbulanceWlListElement;
        new (): HTMLLukasakovaAmbulanceWlListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lukasakova-ambulance-wl-app": HTMLLukasakovaAmbulanceWlAppElement;
        "lukasakova-ambulance-wl-editor": HTMLLukasakovaAmbulanceWlEditorElement;
        "lukasakova-ambulance-wl-list": HTMLLukasakovaAmbulanceWlListElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LukasakovaAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface LukasakovaAmbulanceWlEditor {
        "entryId"?: string;
        "onEditor-closed"?: (event: LukasakovaAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface LukasakovaAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: LukasakovaAmbulanceWlListCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface LukasakovaAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface LukasakovaAmbulanceWlEditorAttributes {
        "entryId": string;
    }
    interface LukasakovaAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "lukasakova-ambulance-wl-app": Omit<LukasakovaAmbulanceWlApp, keyof LukasakovaAmbulanceWlAppAttributes> & { [K in keyof LukasakovaAmbulanceWlApp & keyof LukasakovaAmbulanceWlAppAttributes]?: LukasakovaAmbulanceWlApp[K] } & { [K in keyof LukasakovaAmbulanceWlApp & keyof LukasakovaAmbulanceWlAppAttributes as `attr:${K}`]?: LukasakovaAmbulanceWlAppAttributes[K] } & { [K in keyof LukasakovaAmbulanceWlApp & keyof LukasakovaAmbulanceWlAppAttributes as `prop:${K}`]?: LukasakovaAmbulanceWlApp[K] };
        "lukasakova-ambulance-wl-editor": Omit<LukasakovaAmbulanceWlEditor, keyof LukasakovaAmbulanceWlEditorAttributes> & { [K in keyof LukasakovaAmbulanceWlEditor & keyof LukasakovaAmbulanceWlEditorAttributes]?: LukasakovaAmbulanceWlEditor[K] } & { [K in keyof LukasakovaAmbulanceWlEditor & keyof LukasakovaAmbulanceWlEditorAttributes as `attr:${K}`]?: LukasakovaAmbulanceWlEditorAttributes[K] } & { [K in keyof LukasakovaAmbulanceWlEditor & keyof LukasakovaAmbulanceWlEditorAttributes as `prop:${K}`]?: LukasakovaAmbulanceWlEditor[K] };
        "lukasakova-ambulance-wl-list": Omit<LukasakovaAmbulanceWlList, keyof LukasakovaAmbulanceWlListAttributes> & { [K in keyof LukasakovaAmbulanceWlList & keyof LukasakovaAmbulanceWlListAttributes]?: LukasakovaAmbulanceWlList[K] } & { [K in keyof LukasakovaAmbulanceWlList & keyof LukasakovaAmbulanceWlListAttributes as `attr:${K}`]?: LukasakovaAmbulanceWlListAttributes[K] } & { [K in keyof LukasakovaAmbulanceWlList & keyof LukasakovaAmbulanceWlListAttributes as `prop:${K}`]?: LukasakovaAmbulanceWlList[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lukasakova-ambulance-wl-app": LocalJSX.IntrinsicElements["lukasakova-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLLukasakovaAmbulanceWlAppElement>;
            "lukasakova-ambulance-wl-editor": LocalJSX.IntrinsicElements["lukasakova-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLLukasakovaAmbulanceWlEditorElement>;
            "lukasakova-ambulance-wl-list": LocalJSX.IntrinsicElements["lukasakova-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLLukasakovaAmbulanceWlListElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
